name:                TypeCounting
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/Mijo#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - unordered-containers
  - mtl
  - profunctors
  - hashable
  - ghc-heap

executables:
  TypeCounting:
    source-dirs:      src
    main:             Main.hs
